version: "3.8"

services:
  app:
    build: .
    ports:
      - "${APP_PORT}:3000" 
    environment:
      - DATABASE_URL= ${DATABASE_URL}
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
